
class CreateCase:

        lnkCustomer_menu_xpath = "//body/div[1]/aside[1]/div[1]/nav[1]/div[1]/div[1]/ul[1]/li[2]/a[1]"
        lnkCustomer_menuitem_xpath = "//body/div[1]/aside[1]/div[1]/nav[1]/div[1]/div[1]/ul[1]/li[2]/ul[1]/li[1]/a[1]"
        btncreatecase_xpath = "//input[@id='btn-CreateTotalLossCase']"
        drpInsurer_xpath = "//select[@id='Insurer']"
        txtClaimNumber_xpath = "//input[@id='ClaimInfo_Number']"
        txtRegNum_xpath = "//input[@id='RegistrationNumber']"
        drpRegState_xpath = "//select[@id='RegistrationState']"
        drpAssessParty_xpath = "//select[@id='AssessmentParty']"
        drpAssessInstructions_xpath = "//select[@id='AssessmentInstruction']"
        txtVehicleSupplierName_xpath = "//input[@id='VehicleCurrentLocation_Name']"
        txtVehicleSupplierAddress_xpath = "//input[@id='VehicleCurrentLocation_Address']"
        txtExternalLink_xpath = "//input[@id='ExternalSystemLink']"
        clickPolicy_xpath = "//a[@id='policy-tab']"
        txtPolicyNo_xpath = "//input[@id='PolicyInfo_Number']"
        drpVehicleType_xpath = "//select[@id='PolicyInfo_VehicleType']"
        drpValueCover_xpath = "//select[@id='PolicyInfo_ValueCover']"
        txtAgreedValue_xpath = "//input[@id='PolicyInfo_SumInsured']"
        drpPolicyType_xpath = "//select[@id='PolicyInfo_Type']"
        txtPolicySub_xpath = "//input[@id='PolicyInfo_SubType']"
        txtPolicyInception_xpath = "//input[@id='PolicyInfo_InceptionOdometer']"
        txtRisk_xpath = "//input[@id='PolicyInfo_RiskDescription']"
        drpType_xpath = "//select[@id='accessoryType']"
        txtDesc_xpath = "//input[@id='accessoryDescription']"
        txtValue_xpath = "//input[@id='accessoryValue']"
        clickAddSign_xpath = "//body/div[1]/main[1]/div[1]/form[1]/div[2]/div[2]/div[2]/div[1]/div[5]/div[1]/div[1]/div[1]/div[4]/div[1]/button[1]/i[1]"
        ClickSubSign_xpath = "//tbody/tr[1]/td[4]/i[1]"
        txtEntitled_xpath = "//input[@id='PolicyInfo_ITCEPercent']"
        txtOutstanding_xpath = "//input[@id='PolicyInfo_OutstandingPremium']"
        clickClaim_xpath = "//a[@id='claim-tab']"
        selectDate_xpath = "//input[@id='ClaimInfo_IncidentDate']"
        txtIncidentTime_xpath = "//input[@id='ClaimInfo_IncidentTime']"
        txtIncidentDesc_xpath = "//textarea[@id='ClaimInfo_IncidentDescription']"
        txtDamageDetails_xpath = "//input[@id='ClaimInfo_DamageDetails']"
        txtAirbags_xpath = "//select[@id='ClaimInfo_AirbagsDeployed']"
        txtExcess_xpath = "//input[@id='ClaimInfo_Excess']"
        txtOdometer_xpath = "//input[@id='ClaimInfo_Odometer']"
        clickContact_xpath = "//a[@id='contact-tab']"
        clickOwnerCon_xpath = "//a[@id='owner-tab']"
        clickClaimCon_xpath = "//a[@id='driver-tab']"
        clickBrokerCon_xpath = "//a[@id='broker-tab']"
        txtOwnerName_xpath = "//input[@id='InsuredInfo_Name']"
        txtOwnerPhno_xpath = "//input[@id='InsuredInfo_PhoneNumber_Details']"
        txtOwnerMobileno_xpath = "//input[@id='InsuredInfo_MobileNumber_Details']"
        txtOwneremail_xpath = "//input[@id='InsuredInfo_Email_Details']"
        txtOwnerAdressline_xpath = "//input[@id='InsuredInfo_Address_AddressLine1']"
        txtOwnerAdressline2_xpath = "//input[@id='InsuredInfo_Address_AddressLine2']"
        txtOwnerCity_xpath = "//input[@id='InsuredInfo_Address_City']"
        txtOwnerState_xpath = "//input[@id='InsuredInfo_Address_County']"
        txtOwnerpostcode_xpath = "//input[@id='InsuredInfo_Address_County']"
        txtClaimName_xpath = "//input[@id='DriverInfo_Name']"




